# Generated by Django 3.2.7 on 2021-09-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoList',
            new_name='List',
        ),
    ]
